# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: node config/generateMD.js
    - run: git add README.md
    - run: git status
    - run: git add ./README.MD
    - run: git status
    - name: Commit & push back
      uses: actions-go/push@v1
      with:
        author-email: teachers@codaisseur.com
        author-name: teacher-bot
        remote: origin
        create-commit: true
        commit-message: '[Auto]Checked index.js'
        fail-if-empty: false
        
